{
 "title": "Kube Health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "category",
    "query": {
     "query": "label_values(kube:health,category)"
    }
   },
   {
    "name": "kind",
    "query": {
     "query": "label_values(kube:health{category=~\"$category\"},kind)"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(kube:health,status)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Compute Nodes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (status) (kube:health{category=\"compute\", kind=\"Node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Core Components",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (status) (kube:health{category=\"cluster-core\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logging",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (status) (kube:health{category=\"logging\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (status) (kube:health{category=\"workloads\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube:health{category=~\"$category\",kind=~\"$kind\",status=~\"$status\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}