name: ci
on:
  push:
    branches:
      - main
  pull_request: {}

permissions: read-all

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
